import {
  Bell,
  BriefcaseBusiness,
  Building2,
  Calculator,
  CalendarDays,
  ChartLine,
  CheckSquare,
  Clock,
  Euro,
  FileText,
  Flag,
  House,
  Inbox,
  Layers,
  List,
  Lock,
  MessageCircle,
  PenLine,
  Settings,
  Ticket,
  Trash2,
  TrendingUp,
  UserCheck,
  UserRound,
  Users,
  Video,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/* Icono de cada resultado (claves `i` de la API, las del antiguo). */
export const ICONOS: Record<string, LucideIcon> = {
  clients: Users,
  user: UserRound,
  usercheck: UserCheck,
  check: CheckSquare,
  crm: BriefcaseBusiness,
  trend: TrendingUp,
  file: FileText,
  ticket: Ticket,
  layers: Layers,
  pen: PenLine,
  home: House,
  inbox: Inbox,
  cal: CalendarDays,
  video: Video,
  euro: Euro,
  chart: ChartLine,
  clock: Clock,
  calc: Calculator,
  chat: MessageCircle,
  vault: Lock,
  building: Building2,
  list: List,
  flag: Flag,
  settings: Settings,
  bolt: Zap,
  trash: Trash2,
  bell: Bell,
}

export function Icono({ clave, className }: { clave: string; className?: string }) {
  const I = ICONOS[clave] ?? FileText
  return <I className={className} strokeWidth={1.8} />
}
